import { Footer } from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import SideBar from "@/components/sidebar/SideBar";
import UserService from "@/service/userService";
import { cookies } from 'next/headers'
export const metadata = {
  description: "Generated by create next app",
};

export default async function Layout({ children }) {

  return (
    <div className="relative flex h-full flex-col bg-background">

      <div className="flex flex-col flex-grow">
        <div className="hidden lg:block fixed top-0 left-0 h-full xl:w-[250px] lg:w-[200px] bg-neutral-100 overflow-auto">
          <SideBar />
        </div>
        {children}
        <Footer />
      </div>
    </div>
  );
}
