import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from './../components/navbar/Navbar';
import { Toaster } from 'react-hot-toast';
import AuthService from "@/service/authService";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Toaster position="bottom-right" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
