import { Footer } from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import SideBar from "@/components/sidebar/SideBar";
import AuthService from "@/service/authService";
import { cookies } from 'next/headers'
export const metadata = {
  description: "Generated by create next app",
};

export default async function Layout({ children }) {
  const user = await getServerSideProps();
  return (
    <div className="relative flex h-full flex-col bg-background">
      <Navbar user={user} />
      <div className="flex flex-col flex-grow">
        <div className="hidden lg:block fixed top-0 left-0 h-full xl:w-[250px] lg:w-[200px] bg-neutral-100 overflow-auto">
          <SideBar />
        </div>
        {children}
        <Footer />
      </div>
    </div>
  );
}

async function getServerSideProps() {
  const accessToken = cookies().get('accessToken');
  const refreshToken = cookies().get('refreshToken');
  const res = await AuthService.checkAuth(accessToken, refreshToken);
  if (!res) {
    return null;
  }
  const artist = res.data;
  return artist;
}
